module.exports = {
  apps: [
    {
      name: "omni-ingester",
      script: "python",
      args: "-m services.data_ingester.main",
      cwd: "/opt/omni-trader",
      interpreter: "/opt/omni-trader/venv/bin/python",
      watch: false,
      autorestart: true,
      max_restarts: 20,
      restart_delay: 5000,
      max_memory_restart: "900M",
      env_file: "/opt/omni-trader/.env",
      error_file: "/var/log/omni/ingester-err.log",
      out_file: "/var/log/omni/ingester-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "omni-brain",
      script: "python",
      args: "-m services.ai_brain.main",
      cwd: "/opt/omni-trader",
      interpreter: "/opt/omni-trader/venv/bin/python",
      watch: false,
      autorestart: true,
      max_restarts: 20,
      restart_delay: 5000,
      max_memory_restart: "1G",
      env_file: "/opt/omni-trader/.env",
      error_file: "/var/log/omni/brain-err.log",
      out_file: "/var/log/omni/brain-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "omni-router",
      script: "python",
      args: "-m services.order_router.main",
      cwd: "/opt/omni-trader",
      interpreter: "/opt/omni-trader/venv/bin/python",
      watch: false,
      autorestart: true,
      max_restarts: 20,
      restart_delay: 5000,
      max_memory_restart: "700M",
      env_file: "/opt/omni-trader/.env",
      error_file: "/var/log/omni/router-err.log",
      out_file: "/var/log/omni/router-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "omni-notifier",
      script: "python",
      args: "-m services.notifier.main",
      cwd: "/opt/omni-trader",
      interpreter: "/opt/omni-trader/venv/bin/python",
      watch: false,
      autorestart: true,
      max_restarts: 20,
      restart_delay: 5000,
      max_memory_restart: "400M",
      env_file: "/opt/omni-trader/.env",
      error_file: "/var/log/omni/notifier-err.log",
      out_file: "/var/log/omni/notifier-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
  ],
};
