ALTER TABLE ai_thoughts ADD COLUMN IF NOT EXISTS region TEXT DEFAULT 'US';
ALTER TABLE predictions ADD COLUMN IF NOT EXISTS region TEXT DEFAULT 'US';
ALTER TABLE sentiment_scores ADD COLUMN IF NOT EXISTS region TEXT DEFAULT 'US';
